
exclude: "/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$
  
  # - repo: local
  #   hooks:
  #   - id: pytest-check
  #     name: pytest-check
  #     entry: poetry run pytest
  #     language: system
  #     pass_filenames: false
  #     always_run: true

